# Generated by Django 5.0.6 on 2024-06-23 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0003_transcription_summary_alter_radiostation_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("audio_path", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("summary", models.TextField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streams.radiostation",
                    ),
                ),
            ],
        ),
    ]
